version: '2'
services:
  back:
    container_name: back
    restart: always
    build: ../../back/lingua-server
    environment:
      DEBUG: lingua:*
      PORT: 4000
    ports:
      - "4000:4000"
    volumes:
      - ../../back/lingua-server/src:/usr/www/src
  front:
    container_name: front
    restart: always
    build: ./
    ports:
      - "8080:8080"
    links:
      - back
    volumes:
      - ./src:/usr/www/src
      - ./public:/usr/www/public
